name: Hausaufgabe

on: push

jobs:
  Hausaufgabe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: SSH setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/meinKey.pem
          chmod 400 ~/.ssh/meinKey.pem
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts
      - name: Build Docker image
        run: docker build -t my-frontend ./frontend
      - name: Install Docker on EC2
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{secrets.EC2_IP}} "
         sudo apt update -y &&
         sudo apt install -y docker.io &&
         sudo systemctl enable docker &&
         sudo systemctl start docker
         "
      - name: Save Docker image as tar
        run: docker save my-frontend -o my-frontend.tar
      - name: Copy Docker image to EC2
        run: scp -i ~/.ssh/meinKey.pem my-frontend.tar ubuntu@${{secrets.EC2_IP}}:/home/ubuntu/my-frontend.tar
      - name: Load and run Docker container on EC2
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{secrets.EC2_IP}} "sudo docker load -i /home/ubuntu/my-frontend.tar && sudo docker rm -f my-frontend || true && sudo docker run -d --name my-frontend -p 80:80 my-frontend"
         
      - name: Ordner auf EC2 anlegen
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{ secrets.EC2_IP }} "mkdir -p ~/meinOrdner"
      - name: Datei kopieren
        run: scp -i ~/.ssh/meinKey.pem meinOrdner/info.txt ubuntu@${{ secrets.EC2_IP }}:~/meinOrdner/info.txt
      - name: Check Datei auf EC2
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{ secrets.EC2_IP }} "ls -l ~/meinOrdner && head -n 1 ~/meinOrdner/info.txt"
      - name: Cowsay installieren
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{ secrets.EC2_IP }} "sudo apt update -y && sudo apt install -y cowsay"
      - name: Cowsay ausf√ºhren
        run: ssh -i ~/.ssh/meinKey.pem ubuntu@${{ secrets.EC2_IP }} "cowsay 'Hallo Muhhhhhheib'"
